//AQUI DEVEM SER IMPLEMENTADAS VALIDACOES PARA ABORTAR A EXECUCAO DA PAGINA
function initValidate() {
    return true;
}

//AQUI DEVEM SER IMPLEMENTADOS O BIND DE EVENTOS / MASCARAS
function aplicaEventos() {

}

//AQUI DEVEM SER IMPLEMENTADO A FUNCAO PARA GUARDAR OS VALORES ANTES DO CARREGAMENTO POIS SERAO RESTAURADOS NO RESTAURAVALORES
function guardaValores() {

}

//AQUI DEVEM SER IMPLEMENTADOS OS CARREGAMENTOS DE DATASETS PARA PREENCHER SELECTS E AUTOCOMPLETES
//NAO DEVERA SER SETADO NENHUM VALOR PADRAO O MESMO DEVE SER FEITO NO METODO NOVO REGISTRO
//NAO DEVERA SER RESTAURADO NENHUM VALOR O MESMO DEVERA SER FEITO NO RESTAURA VALORES APOS O CARREGAMENTO
function preencheDados() {

}

//AQUI DEVE SER RESTAURADOS OS DADOS GUARDADOS NO GUARDA VALORES
function restauraValores() {

}

//AQUI DEVEM SER RESTAURADOS OS ESTADOS DA TELA, COMO EXIBIR OU OCULTAR ELEMENTOS
function restauraEstados(novoRegistro) {

}

//AQUI DEVEM SER PREENCHIDOS OS CAMPOS COM VALORES DEFAULT E INICIALIZACOES PADROES PARA UM NOVO REGISTRO
function novoRegistro() {
    $('#data_escopo').val(moment().format('DD/MM/YYYY'));
}

function addChildCronograma() {
    var row = wdkAddChild('cronograma');
    FLUIGC.calendar('#atividade_inicio___' + row);
    FLUIGC.calendar('#atividade_fim___' + row);
}

function gerarPdfEscopo() {

}
